version: '3'

services:

  app:
    build: .
    image: node:latest
    container_name: receitinha-aps
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./packages/gateway:/home/node/app
      - ./packages/gateway/node_modules:/home/node/app/node_modules
    command: yarn dev